name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential cmake

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure

